package org.example.test.repositories;

import org.example.test.models.Personnel;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 25/04/2024
*/
@Repository
public interface PersonnelRepository extends JpaRepository<Personnel, Long> {

}
